services:
  airflow-init:
    build: .
    env_file:
      - .env
    entrypoint: ["/bin/bash", "-c", "airflow db init"]
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: ${STR_BD_CONN}
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      _AIRFLOW_WWW_USER_USERNAME: santiago
      _AIRFLOW_WWW_USER_PASSWORD: santiMeneses2024
    networks:
      - cluster-datos

  webserver:
    build: .
    env_file:
      - .env
    container_name: airflow_webserver
    restart: always
    command: webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: ${STR_BD_CONN}
      AIRFLOW__CORE__LOAD_EXAMPLES: False
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: True
      _AIRFLOW_WWW_USER_USERNAME: santiago
      _AIRFLOW_WWW_USER_PASSWORD: santiMeneses2024
    volumes:
      - ./dags:/data/airflow/dags
      - ./logs:/data/airflow/logs
      - ./plugins:/data/airflow/plugins
    ports:
      - "8080:8080"
    depends_on:
      - airflow-init
    networks:
      - cluster-datos

  scheduler:
    build: .
    env_file:
      - .env
    restart: always
    command: scheduler
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: ${STR_BD_CONN}
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      _AIRFLOW_WWW_USER_USERNAME: santiago
      _AIRFLOW_WWW_USER_PASSWORD: santiMeneses2024
    depends_on:
      - airflow-init
    networks:
      - cluster-datos

networks:
  cluster-datos:
    external: true


    