version: '1'
services:
  bd-mysql-1:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLPASS}
      MYSQL_DATABASE: bdnegocio
      MYSQL_USER: santi
      MYSQL_PASSWORD: ${MYSQLPASS}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
networks:
  cluster-datos:
    external: true
volumes:
  mysql_data: