services:
  mysql:
    image: mysql:latest
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: bdMonitoreo
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - cluster-datos
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1GB
      restart_policy:
        condition: unless-stopped
    logging:
      driver: "journald"
networks:
  cluster-datos:
    external: true
volumes:
  mysql_data: